<!DOCTYPE html>
<html lang="en">
<head>
<title>IASF</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "Lato", sans-serif}
.mySlides {display: none}
</style>


<style>
.slideshow {
position: relative;
overflow: hidden;
}
.imgslide {
background: url(images/image.png);
position: absolute;
left: 0;
top: 0;
height: 100%;
width: 300%;
animation: slideshow 10s linear infinite;
}
@keyframes slideshow {
0%    { left: 0; }
100%  { left: -200%; }
}



</style>



</head>
<body>

<!-- Navbar -->
<center><div class="w3-top">
  <div class="w3-bar w3-black w3-card">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="index.php" class="w3-bar-item w3-button w3-padding-large">HOME</a>
    <a href="sta.php" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Statistics</a>
    <a href="more.php" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Learn More</a>
    
    
  </div>
</div>
</center>

<!-- Navbar on small screens (remove the onclick attribute if you want the navbar to always show on top of the content when clicking on the links) -->

<!-- Page content -->
<div class="w3-content" style="max-width:2000px;margin-top:46px">

  <!-- Automatic Slideshow Images -->
  <div class="mySlides w3-display-container w3-center">
    <img src="images/w1.jpeg" style="width:40%">
    <div class="w3-display-bottommiddle w3-container w3-text-white w3-padding-32 w3-hide-small">
     
    </div>
  </div>

  <div class="mySlides w3-display-container w3-center">
    <img src="images/w2.jpeg" style="width:40%">
    <div class="w3-display-bottommiddle w3-container w3-text-white w3-padding-32 w3-hide-small">
     
    </div>
  </div>

  <div class="mySlides w3-display-container w3-center">
    <img src="images/w3.jpeg" style="width:40%">
    <div class="w3-display-bottommiddle w3-container w3-text-white w3-padding-32 w3-hide-small">
      
    </div>
  </div>
  

  <!-- The Band Section -->
  <div class="w3-container w3-content w3-center w3-padding-64" style="max-width:800px" id="band">
    <h1 class="w3-wide">Power, Pollution and the Internet</h1>
    
    <h3 class="w3-justify">The company had been packing a 40-by-60-foot rental space here with racks of
computer servers that were needed to store and process information from members’
accounts. The electricity pouring into the computers was overheating Ethernet
sockets and other crucial components.
Thinking fast, Mr. Rothschild, the company’s engineering chief, took some employees
on an expedition to buy every fan they could find — “We cleaned out all of the
Walgreens in the area,” he said — to blast cool air at the equipment and prevent the
Web site from going down.
That was in early 2006, when Facebook had a quaint 10 million or so users and the
one main server site. Today, the information generated by nearly one billion people
requires outsize versions of these facilities, called data centers, with rows and rows
of servers spread over hundreds of thousands of square feet, and all with industrial
cooling systems.
They are a mere fraction of the tens of thousands of data centers that now exist to
support the overall explosion of digital information. Stupendous amounts of data are
set in motion each day as, with an innocuous click or tap, people download movies on
iTunes, check credit card balances through Visa’s Web site, send Yahoo e-mail with
files attached, buy products on Amazon, post on Twitter or read newspapers online. 

Worldwide, the digital warehouses use about 30 billion watts of electricity, roughly
equivalent to the output of 30 nuclear power plants, according to estimates industry
experts compiled for The Times. Data centers in the United States account for
one-quarter to one-third of that load, the estimates show.
“It’s staggering for most people, even people in the industry, to understand the
numbers, the sheer size of these systems,” said Peter Gross, who helped design
hundreds of data centers. “A single data center can take more power than a
medium-size town.”
Energy efficiency varies widely from company to company. But at the request of The
Times, the consulting firm McKinsey & Company analyzed energy use by data
centers and found that, on average, they were using only 6 percent to 12 percent of
the electricity powering their servers to perform computations. The rest was
essentially used to keep servers idling and ready in case of a surge in activity that
could slow or crash their operations.
</h3>

<h1> 
Re-think Your Next Tech Purchase</h1><br>
This one is pretty obvious but also the hardest step for people who love tech. You don’t need the latest tech gadget! Let me repeat that, you don’t need the latest tech gadget! One of the biggest contributors to digital pollution is the disposal of technology, which can be greatly reduced if you think before you buy. If you have a perfectly functioning laptop or mobile device, rethink your desire to replace it with the newest shiniest thing.

<h1>Recycle Old Electronics</h1><br>
Do you stash all your old electronics in a closet? Here’s your sign to recycle them! I know this is always an “I’ll do that later” situation, but do Mother Earth a favour and send them to a recycling program. Please don’t throw your devices in the trash. With a quick search you can find a recycling program in your area, which brings us to our next tip.

<h1>Use a Green Search Engine</h1><br>
The search engine Ecosia uses its profits from paid advertisers to fund reforestation projects. Involved with 9,000 planting sites, they’ve already helped plant over 123 million trees all over the world! Reforestation is an important cause for so many communities because trees do so much more than absorb CO2. Trees can restart water cycles, protect and create wildlife habitat, improve soil fertility, and overall uplift local communities. That’s a lot of good for a simple search.

<h1>Monitor Your Inbox</h1><br>
Emails seem innocent enough, but one email produces 4g of CO2. That number on its own isn’t significant but think about all the emails you’ve accumulated in your inbox over the last year. If you’re not using Slack, an employee can receive and send about 121 emails a day… Imagine how quickly the CO2 adds up. Instead of letting your emails accumulate in your inbox delete the ones you’ll never open. Bonus points if you delete and unsubscribe from the newsletters you never bother opening.

<h1>Delete Unused Tabs</h1><br>
Not only does it make your computer run slower, having a bunch of unnecessary tabs open drains your computer’s battery. I’m definitely guilty of having way too many tabs open. Sometimes you just want to save a tab for later, I get it! But every time you open a web page, it uses CO2. If you want to know exactly how much, test a web page on the Website Carbon Calculator. Oops, I just made you open another tab.


If you have trouble closing tabs on a regular basis, try using the Tabbs Google Chrome extension. It can automatically close the tabs you haven’t opened in a while, allowing your computer to run smoother throughout the day.

<h1>Download Your Music</h1><br>
Over 75% of workers will listen to music on the job, and if you’re streaming on Spotify or Apple Music you’re transferring quite a lot of data. The initial download of a song uses the same amount of data as streaming it, however, downloading it stores it in your computer’s memory. If you have a Spotify playlist that you listen to every day it’s definitely worth the download.

<h1>Turn Down Your Brightness</h1><br>
An energy manager from Harvard Law School found that reducing your monitor’s brightness from 100% to 70% can save 20% of the energy your monitor uses. Plus you won’t notice much of a difference so this one is an easy switch.

<h1>Use Your Address Bar</h1><br>
Do you ever make a search enquiry for Facebook without thinking twice about it? Or worse, do you ever search for Google in Google? Using a search engine instead of typing a URL into your browser’s address bar is leading to a bunch of useless data processing. If you’re going to a website you visit often use the address bar. You’ll get to your page faster and produce less carbon! A win-win.

Another way you can reduce your carbon footprint is by bookmarking the pages you use often.
</h1>
    

    

</body>
</html>
